In [71]:
import scipy.io as sio
import numpy as np
from sklearn import preprocessing
import DataLoader as dl

# Binarization preprocessing
def binarization(a):
	binarizer = preprocessing.Binarizer().fit(a)
	return binarizer.transform(a)

# Compute Maximum Likelihood Estimation of lambda
def getLambdaML(data):
	a = np.array(data)
	unique, counts = np.unique(a, return_counts=True)
	labels = dict(zip(unique, counts))
	# ML Estimate of lambda = N1/N
	lambdaMl = labels[1]/(labels[0]+labels[1])
	return lambdaMl, labels[0], labels[1]+labels[0]

def getNbClassifier(xtrain, ytrain):
	# lambdaMl = getLambdaML(ytrain)
	# Separate xtrain by class/label
	spam = []
	nonspam = []
	for i in range(len(xtrain)):
		vector = xtrain[i]
		if ytrain[i] == 0:
			nonspam.append(vector)
		else:
			spam.append(vector)
	spam = np.array(spam).astype(int)
	nonspam = np.array(nonspam).astype(int)
	# calculate Xcj matrix
	numFeatures = spam.shape[1]
	print('Feauture Number: ', numFeatures)
	x = np.zeros((2, numFeatures)).astype(int)
	x[1] = np.sum(spam, axis=0)
	x[0] = np.sum(nonspam, axis=0)
	print(x[0])
	print(x[1])
	return x

def getPredictions(classifier, xtest):
	return

In [72]:
# Load data from spamData.mat
xtrain, ytrain, xtest, ytest = dl.loadData('matlab.mat')
xtrain = binarization(xtrain)
xtest = binarization(xtest)
print(xtrain)

[[1 0]
 [1 1]
 [0 1]
 [0 0]]


In [73]:
# Get classifier
naiveBayesClassifier = getNbClassifier(xtrain, ytrain)

Feauture Number:  2
[0 1]
[2 1]


In [75]:
# Get Maximum Likelihood Estimation of lambda
lambdaML, N1, N = getLambdaML(ytrain)
print(getLambdaML(ytrain))

(0.5, 2, 4)


In [76]:
# Create an array of alpha values, from 0 to 100 with step size 0.5
alphaStart = 0
alphaEnd = 1
alphaStepSize = 0.5
alphaArr = np.arange(alphaStart, alphaEnd + alphaStepSize, alphaStepSize)
print(alphaArr)

[0.  0.5 1. ]


In [77]:
# Initialise an array of error rate
errRate = np.zeros(alphaArr.size)
print(alphaArr.size)

3


In [ ]:
def calcPosteriorProdictiveDist(alpha, lambdaMl, featureVector):
	# Initialise
	logP_yTilde_1 = math.log(lambdaMl)
	logP_yTilde_0 = math.log(1 - lambdaMl)

	# Calculate  logP(yTilde = 1 | xTilde, D)
	for i in range(featureVector):
		if feature:
	else:

    # Calculate  logP(yTilde = 0 | xTilde, D)
    

In [49]:
for alpha in np.nditer(alphaArr):
	print('alpha', alpha)
    
	for featureVector in xtest:
		print('featureVector', featureVector)
		print(calcPosteriorProdictiveDist(alpha, naiveBayesClassifier, lambdaMl, featureVector))


alpha 0.0
featureVector [1 0]
featureVector [1 1]
featureVector [0 0]
alpha 0.5
featureVector [1 0]
featureVector [1 1]
featureVector [0 0]
alpha 1.0
featureVector [1 0]
featureVector [1 1]
featureVector [0 0]


In [44]:
naiveBayesClassifier

array([[0, 1],
       [2, 1]])

In [50]:
featureVector = xtest[0]
np.multiply(naiveBayesClassifier, featureVector)

array([[0, 0],
       [2, 0]])

In [52]:
featureVector = xtest[1]
np.multiply(naiveBayesClassifier, featureVector)

array([[0, 1],
       [2, 1]])

In [55]:
featureVector = xtest[2]
np.multiply(naiveBayesClassifier, featureVector)

array([[0, 0],
       [0, 0]])

In [56]:
xtest[1]

array([1, 1], dtype=uint8)

In [62]:
if 1:
    print('ok')
else:
    print('zero')

ok
