In [22]:
import scipy.io as sio
import numpy as np
from sklearn import preprocessing
import DataLoader as dl

def loadData(fileName):
	mat = sio.loadmat(fileName)
	xtest = mat['Xtest']
	xtrain = mat['Xtrain']
	ytest = mat['ytest']
	ytrain = mat['ytrain']
	return xtrain, ytrain, xtest, ytest

# Binarization preprocessing
def binarization(a):
	binarizer = preprocessing.Binarizer().fit(a)
	return binarizer.transform(a)

# Compute Maximum Likelihood Estimation of lambda
def getLambdaML(data):
	a = np.array(data)
	unique, counts = np.unique(a, return_counts=True)
	labels = dict(zip(unique, counts))
	# ML Estimate of lambda = N1/N
	return labels[1]/(labels[0]+labels[1])

def getNbClassifier(xtrain, ytrain):
	# lambdaMl = getLambdaML(ytrain)
	# Separate xtrain by class/label
	spam = []
	nonspam = []
	for i in range(len(xtrain)):
		vector = xtrain[i]
		if ytrain[i] == 0:
			nonspam.append(vector)
		else:
			spam.append(vector)
	spam = np.array(spam).astype(int)
	nonspam = np.array(nonspam).astype(int)
	# calculate Xcj matrix
	numFeatures = spam.shape[1]
	print('Feauture Number: ', numFeatures)
	x = np.zeros((2, numFeatures)).astype(int)
	x[0] = np.sum(spam, axis=0)
	x[1] = np.sum(nonspam, axis=0)
	print(x[0])
	print(x[1])
	return x

def getPredictions(classifier, xtest):
	return

In [23]:
# Load data from spamData.mat
xtrain, ytrain, xtest, ytest = dl.loadData()
xtrain = binarization(xtrain)
xtest = binarization(xtest)

In [32]:
print(xtrain)
# Get classifier
naiveBayesClassifier = getNbClassifier(xtrain, ytrain)
print(getLambdaML(ytrain))

[[0. 0. 0. ... 1. 1. 1.]
 [0. 0. 0. ... 1. 1. 1.]
 [0. 1. 1. ... 1. 1. 1.]
 ...
 [0. 0. 0. ... 1. 1. 1.]
 [1. 0. 1. ... 1. 1. 1.]
 [0. 0. 0. ... 1. 1. 1.]]
Feauture Number:  57
[ 431  433  760   25  783  457  523  444  394  582  391  785  357  151
  202  692  489  476 1102  274 1006   57  416  461   38   18    7   19
    8    9    3    2   48    7   37   81   72   23   51  144    1   12
   58   28  321   54   12   11  191  801   88 1033  761  358 1240 1240
 1240]
[ 260  176  497    6  394  218   29  140  135  319   96  776  203   82
   33  172  168  227 1037   29  617    9   52   35  672  508  499  274
  227  280  176  127  229  128  267  309  471   34  210  155   94  204
  182  166  526  287   26  122  337 1000  249  479  184  146 1825 1825
 1825]
0.40456769983686786


In [34]:
# test model
# predictions = getPredictions(summaries, xtest)
# accuracy = getAccuracy(ytest, predictions)
# print('Accuracy: {0}%').format(accuracy)


In [33]:
# Create an array of alpha values, from 0 to 100 with step size 0.5
alpha = np.arange(0, 100.5, 0.5)